### ISSUE TITLE
[REQUEST] Kvantum Support

### ISSUE THREAD

**Issue by Sparklytical** [baduhai/Koi#1]
**Is your feature request related to a problem? Please describe.**
You can add Kvantum Theme Engine support as it also supports changing theme through the command line.
**Describe the solution you'd like**
I have set of scripts that do that for Kvantum, you can check on them 
https://github.com/EvilSpark/Kde-Scripts

**Additional context**
Kvantum Theme changing support in koi

**Comment by baduhai** [comment]
I expected this to be one of the first feature requests :laughing:. I'll work on it for future releases. If you'd like to open a pull request, I'd be happy to merge into master! :wink:

**Comment by cochonez** [comment]
this would be so f..... awesome *_*

**Comment by Da-Viper** [comment]
> this would be so f..... awesome ___

it is now available if you build from git

**Comment by baduhai** [comment]
And will be available on the next release :wink:

**Comment by baduhai** [comment]
And will be available on the next release thanks to @Da-Viper!

**Comment by Da-Viper** [comment]
Also gtk theme now update on the fly in plasma 5.19

**Comment by baduhai** [comment]
This has been a thing for a while now, guess I forgot about closing this issue.
