### ISSUE TITLE
[OTHER]development environment for the app

### ISSUE THREAD

**Issue by Da-Viper** [baduhai/Koi#14]
i tried to use vscode and clion and clone the app but it is not working as it requires cmake and the application uses qmake is there any way to make it work  or what appcation or setup you use for developing the app and how to set it up 

thanks ( i am kind of a noob at c++  )

**Comment by baduhai** [comment]
The README.md file contains instructions for compiling the program manually. I personally use QtCreator for development. If you'd like to set up this project for development under QtCreator, simply install it, and you can import the project using QtCreator's import wizard which allows you to import a git project.

I'm closing this issue as it's not exactly a problem with Koi or Koi development, but feel free to post further comments here, I'm more than happy to help.
