### ISSUE TITLE
[REQUEST] Add ability to run custom command on toggling

### ISSUE THREAD

**Issue by amr3k** [baduhai/Koi#16]
please allow to run a custom command/script when toggling, like I have a simple conky widget which text is black on white wallpaper, It would be cool if I'm able to switch that conky script based on Koi's trigger (making another script that has white text in dark mode).
other apps also don't follow system theme like Jetbrains' apps (PyCharm, etc) , I imagine a simple script would do all the tricks.

**Comment by baduhai** [comment]
Please look at other issues before opening a new one, this is a duplicate.

**Comment by baduhai** [comment]
Closed as duplicate.
