### ISSUE TITLE
[BUG] 0.1.1 Error & SegFault on start

### ISSUE THREAD

**Issue by lifeintimelapse** [baduhai/Koi#18]
**Describe the bug**
0.1.1 builds and installs without issue, but crashes when run:

```
QSocketNotifier: Can only be used with threads started with QThread
Segmentation Fault
```

 - Distro: Kubuntu 20.04
               KDE Plasma 5.18.5
               KDE Frameworks 5.68.0
               Qt 5.12.8
 - Version 0.1.1

I tried an upgrade (git pull and rebuild/reinstall) then a clean clone and build/install having removed the existing config file, followed by a reboot. Same result in both cases. 

Uninstalled and reverted to 0.1, it's running fine as before. BTW, the uninstall script gave me a start as it has some dangerous looking (although effectively harmless, thank god) commands:

<pre><code>
rm -f /usr/bin/Koi
rm -f /usr/bin/Koi
<b>rmdir /usr/bin/
rmdir: failed to remove '/usr/bin/': Directory not empty</b>
make: [Makefile:747: uninstall_target] Error 1 (ignored)
rm -f -r /usr/share/applications/koi.desktop
<b>rmdir /usr/share/applications/
rmdir: failed to remove '/usr/share/applications/': Directory not empty</b>
make: [Makefile:756: uninstall_desktop] Error 1 (ignored)
rm -f -r /usr/share/icons/hicolor/scalable/apps/koi_tray.svg
rm -f -r /usr/share/icons/hicolor/scalable/apps/koi.svg
<b>rmdir /usr/share/icons/hicolor/scalable/apps/
rmdir: failed to remove '/usr/share/icons/hicolor/scalable/apps/': Directory not empty</b>
make: [Makefile:767: uninstall_icons] Error 1 (ignored)
</code></pre>

**Comment by Seqularise** [comment]
I tried to make Koi-git pkgbuild, result gives me the same error

**Comment by baduhai** [comment]
> Koi-git pkgbuild

I am unaware of any such pkgbuild. The only pkgbuild I provide is on the [AUR](https://aur.archlinux.org/packages/koi/). If you'd like to install Koi, do it from there, if you must compile, download a [release](https://github.com/baduhai/Koi/releases). Compiling from the master branch can lead to error such as the one mentioned in this very thread.

**Comment by Seqularise** [comment]
> > Koi-git pkgbuild
> 
> I am unaware of any such pkgbuild. The only pkgbuild I provide is on the [AUR](https://aur.archlinux.org/packages/koi/). If you'd like to install Koi, do it from there, if you must compile, download a [release](https://github.com/baduhai/Koi/releases). Compiling from the master branch can lead to error such as the one mentioned in this very thread.

I made my own pkgbuild, actually it would be nice to have "official" -git package in aur.

**Comment by baduhai** [comment]
The reason I don't have koi-git on the AUR is exactly because of the possibility of issues just like this one popping up. If you'd like to submit your pkgbuild to the AUR I wouldn't mind linking to it on the README.

**Comment by baduhai** [comment]
0.1.1 no longer supported, open a new issue if still facing the problem.
