### ISSUE TITLE
[REQUEST] Add Flatpak support

### ISSUE THREAD

**Issue by TobiPeterG** [baduhai/Koi#19]
**Is your feature request related to a problem? Please describe.**
The build might fail on systems due to missing dependencies or version mismatches and it's not that easy to find the project.

**Describe the solution you'd like**
Adding flatpak support would solve the issues stated above.

**Describe alternatives you've considered**
Snap or Appimage support, but flatpak seems to be the better alternative.

**Comment by probonopd** [comment]
Why do you think that AppImage would be less desirable?

**Comment by TobiPeterG** [comment]
I can't build the app image due to a missing dependencies on my Tumbleweed system.
That would not happen, if the program was provided as flatpak.

Also, imo, flatpak does better integrate into the system than appimage. But that's just my experience.

**Comment by baduhai** [comment]
I'm still undecided on whether or not to add Flatpak support. My problem with AppImage is that it doesn't use the Breeze style without me having to package Breeze in the AppImage. That in and of itself is only an annoyance, the actual problem, is that if a Koi user is using some Qt Style other than Breeze(which isn't unlikely, given there's people asking for Kvantum support), Koi will look very out of place. It is my understanding that the same poblem will arise with Flatpak, but at least (I think) I won't have to package Breeze, and it will use Breeze by default.

**Comment by probonopd** [comment]
> My problem with AppImage is that it doesn't use the Breeze style without me having to package Breeze in the AppImage

Well, that is a conceptual problem: An AppImage is supposed to run on systems that have no KDE or Qt installed, so they won't have Breeze installed either. Consequently, if you like your app to use Breeze, you need to bundle a private copy of it in the AppImage. So I'd say if your application looks best with Breeze, then just bundle Breeze...

**Comment by TobiPeterG** [comment]
The only option I see to solve that issue would be to package it as Deb / RPM to be able to access the system libs etc.
Otherwise I don't see a solution to that.

Bundling breeze with the appimage would make the package way bigger and I don't know if it's worth that.

**Comment by baduhai** [comment]
> The only option I see to solve that issue would be to package it as Deb / RPM to be able to access the system libs etc.
> Otherwise I don't see a solution to that.

That's just way too much added work for me. I'm only willing to support an AUR package and a distro agnostic distribution method.

> It can be done with AppImages by bundling e.g., the KDE and Gtk `plugins/platformthemes`.

I didn't know about this. Might just convince me to bundle an AppImage again. This is a problem that I encountered when researching AppImages and Flatpaks, while you can find nice documentation, when it comes to things which are just a little bit more specific than what the official documentation provides, information becomes quite obscure. A quick [search](https://docs.appimage.org/search.html?q=platformthemes&check_keywords=yes&area=default) of `platformthemes` on the official docs returns nothing, had you not told me about `plugins/platformthemes`, I would never have found out about it.

> Also check out https://github.com/KDE/plasma-integration.

Pretty interesting. Seems like a perfect fit for what I need.

**Comment by probonopd** [comment]
Yes, the whole Qt theming situation is a bit of a mess imho (not only with AppImage). But remember, since an AppImage is just a self-mounting filesystem image that executes whatever you put inside it, it gives you most flexibility to do whatever you like.

So, question: What shall happen on systems that don't have KDE/Breeze?

**Comment by baduhai** [comment]
Not doing flatpak, that would be an absolutely massive pain in the ass. Check out the [nix](https://nixos.org/download.html) package manager, which I have a build script for. I might also bring back the appimage once I figure out building appimages with nix.

**Comment by eylenburg** [comment]
@MartinVonReichenberg would you consider packaging this as Flatpak? Koi is in no "official" repo, just AUR/OBS/COPR so if this can be run as a Flatpak it would simplify the installation.

**Comment by MartinVonReichenberg** [comment]
> @MartinVonReichenberg would you consider packaging this as Flatpak? Koi is in no "official" repo, just AUR/OBS/COPR so if this can be run as a Flatpak it would simplify the installation.


Consider yes, 

How & when (if ever) to build it I have no clue . . .

_Koi is in SUSE TumbleWeed repositories, but despite that, since there is not so big general interest in this program, I can't do anything else about it._
