### ISSUE TITLE
[QUESTION] getColorSchemes vs get ColorSchemesPath

### ISSUE THREAD

**Issue by cyclinggeorgian** [baduhai/Koi#23]
in the "Get Stuff" block of the utils.cpp program there are two statements that seem to do the same thing:
QStringList Utils::getColorSchemes(void) and
QStringList Utils::getColorSchemesPath(void)

not a cpp programmer so forgive my ignorance, but i was wandering if program can do without later... in the spirit of keeping code "lean and mean" :-)

**Comment by Da-Viper** [comment]
yeah i do agree with you the path of the colour scheme method is not actually used and what it does can be accomplished by the same getColorschemes();

**Comment by cyclinggeorgian** [comment]
thanks for reply. closing issue... lets keep issue tracker "lean" as well :-)

**Comment by baduhai** [comment]
I'm reopening this, as I was going through the code, and this irked me as well. I don't know why exactly I did things this way, I'm sure there was a reason, but I think I know how to resolve this, I just need to figure out qt regex with QStringLists.

**Comment by MartinVonReichenberg** [comment]
Seems as irrelevant nowadays.

If anybody has an appropriate idea on this topic, can re-open the issue.

_I am closing it due to lack of interest and inactivity . . ._
