### ISSUE TITLE
[OTHER] Are you still interested in maintain this project ? 

### ISSUE THREAD

**Issue by Da-Viper** [baduhai/Koi#28]
Hello there. 

i have been trying to get hold of you for sometime, but could not. 
i am not sure if you still intend on maintain as you have not been active for sometime now,  i feel like i need to fork the project and just continue on with it, since i don't know of your current situation.

the reason i have not done so yet i do not want it to be another "switcher" or making Yet another .........

i have had the merge request for sometime now waiting for a feedback from you, have not received any yet . 
that is why the above question exists.

**Comment by baduhai** [comment]
Hey Da-Viper, 
Yes, I still want to maintain this project. The reason I didn't see your comments on the pull request is because I've been getting so many email about the commits you've been making on that pull request that I started ignoring them. I'll have a look asap, and give you some feedback.

**Comment by Da-Viper** [comment]
oh ok
