### ISSUE TITLE
[BUG] Dark to Light Toggle: GTK Theme Doesn't Switch to Light

### ISSUE THREAD

**Issue by BrdLaw** [baduhai/Koi#29]
**Describe the bug**
When toggling between themes, "gtk-application-prefer-dark-theme=true" is written to the gtk-3.0/settings.ini config file. This line persists between light/dark toggling and causes gtk applications to continue displaying the dark colors of the theme when switched to light. 

**To Reproduce**
1. Toggle from dark to light theme
2. Open ~/.config/gtk-3.0/settings.ini in editor
3. First line: "gtk-application-prefer-dark-theme=true" is still present

**Expected behavior**
I expect gtk themes to toggle appropriately and it seems the above line in the config file is redundant in setting gtk colors in KDE. From my understanding, if the gtk theme has both light and dark themes in the same folder, i.e. "Breeze", they will follow the color scheme set in the Color section of the System Settings. The other case would be having two separate themes with their own light or dark theme, i.e "Arc" and "Arc-Dark", but in that case, the gtk theme has it's own colors to follow and the "prefer-dark-theme=true" is still redundant.

**Desktop (please complete the following information):**
Operating System: EndeavourOS
KDE Plasma Version: 5.20.1
KDE Frameworks Version: 5.75.0
Qt Version: 5.15.1
Kernel Version: 5.9.1-arch1-1
OS Type: 64-bit
Processors: 8 × Intel® Core™ i7-4710MQ CPU @ 2.50GHz
Memory: 15.5 GiB of RAM
Graphics Processor: Mesa DRI Intel® HD Graphics 4600

**Comment by dasbaumwolltier** [comment]
The qdbus method setGtkTheme2/setGtkTheme3 was renamed to setGtkTheme in KDE 5.19.90/5.20.0

**Comment by vroger11** [comment]
@baduhai I think this issue should be closed.
