### ISSUE TITLE
Some color change activations require kwin_x11 --replace

### ISSUE THREAD

**Issue by erwin** [baduhai/Koi#34]
Some color scheme options are not activated until kwin is restarted.

**To Reproduce**
1. Set Koi like this:
![image](https://user-images.githubusercontent.com/11534217/136878157-39b6bc5a-907a-4fd3-82cf-ac56616fd6e9.png)
2. Toggle from Dark to Light Mode or Light to Dark mode
3. The "breeze high contrast" color scheme has a blue titlebar
4. You won't see that blue titlebar when switching via Koi, but you do see it when toggling via System Settings > Appearance > Colors: 
5. If you manually restart `kwin` in a terminal with `kwin_x11 --replace` the color settings are activated.

**Expected behavior**
Expected Koi's Color change setting to work the same as System Preferences

**Screenshots**

### Koi Light Mode as it works now
![image](https://user-images.githubusercontent.com/11534217/136878820-affb7c01-eb41-4329-a316-e8e7d5bc2b95.png)

### Koi Dark Mode as it works now
![image](https://user-images.githubusercontent.com/11534217/136878905-0b58592c-cbf0-42b3-ade5-4f726579a845.png)

### Light Mode If I also run `kwin_x11 --replace`
![image](https://user-images.githubusercontent.com/11534217/136879092-19804a26-3894-41df-b6e1-580647a9b578.png)

**Desktop (please complete the following information):**
 - Distro: Kubuntu 21.04 x86_64
 - Plasma 5.21.4
- X11 not Wayland

**Additional context**

- My suggestion is to add a "restart kwin" checkbox to the Koi Preferences, so that people can optionally do this if needed...
- Or to add a "Light Command" and "Dark Command" so that we can use Koi to trigger this change, and also to cascade that out to other programs that we want to reconfigure.

**Comment by baduhai** [comment]
I believe this is no longer required, reopen if I'm incorrect, I don't use x any more.
