### ISSUE TITLE
[REQUEST] Add OnlyOffice themes

### ISSUE THREAD

**Issue by bphd** [baduhai/Koi#35]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by baduhai** [comment]
Out of scope, explanation [here](https://github.com/baduhai/Koi/issues/4#issuecomment-1215777253).

**Comment by bphd** [comment]
https://github.com/baduhai/Koi/issues/46#issuecomment-1216228931 well you should !!!

**Comment by baduhai** [comment]
Changing color schemes in Plasma also toggles the `org.freedesktop.appearance.color-scheme` option. It is then up to other applications to follow the free desktop specification.

**Comment by bphd** [comment]
(you should close properly I mean lol)
