### ISSUE TITLE
[REQUEST] Changing Sublime, Konsole, Chrome theme

### ISSUE THREAD

**Issue by netship02** [baduhai/Koi#4]
Able to change konsole profile, sublime profile(if possible), and chrome dark mode for dark theme.
I am currently changing konsole default profile by editing konsolerc default profile (lol) using 'sed' command.

**Comment by baduhai** [comment]
Need to evaluate the feasibility of adding these features, though at first glance they don't seem too difficult to do.

**Comment by Derpitron** [comment]
I think being able to change Yakuake theme would be nice too.

**Comment by kupiqu** [comment]
Excellent work! 

May I add libreoffice (and maybe firefox) to the list?

**Comment by baduhai** [comment]
> and maybe firefox

Firefox follows GTK, so no need.

**Comment by netship02** [comment]
Maybe a Text field where we can add custom command to execute. 
Is it possible?

**Comment by baduhai** [comment]
> Maybe a Text field where we can add custom command to execute.
> Is it possible?

It's very much possible, and was in my mind as a feature for future versions! :wink:

**Comment by kupiqu** [comment]
> Firefox and LibreOffice follow GTK, so no need.

Sure, but having in libreoffice a dark frame yet black text over white background is not of much help. Probably difficult but it would be great to tweak Libreoffice settings too (worse case scenario, libreoffice is open and the user needs to restart, but restarting is much easier and faster than tweaking back and forth libreoffice settings every single time)

**Comment by kupiqu** [comment]
> > Firefox and LibreOffice follow GTK, so no need.
> 
> Sure, but having in libreoffice a dark frame yet black text over white background is not of much help. Probably difficult but it would be great to tweak Libreoffice settings too (worse case scenario, libreoffice is open and the user needs to restart, but restarting is much easier and faster than tweaking back and forth libreoffice settings every single time)

Actually it would be great to have a setting for dark background and light foreground that could be applied to documents in applications such as libreoffice, okular, etc.

I'm thinking wild, probably difficult and not worth it. If that is the case, I understand.

**Comment by aronkvh** [comment]
> Firefox follows GTK, so no need.
is there a chance you can add Firefox color support?

**Comment by baduhai** [comment]
I have decided that I don't want koi to handle the theme changes of any specific program. I will eventually make it so koi can trigger scripts when changing themes, and users can implement these changes themselves. Closing as out of scope.

**Comment by bphd** [comment]
Maybe that can help to automatize

coolor=darklight; echo set $coolor; ln --symbolic /home/$USER/.config/yakuakerc-$coolor /home/$USER/.config/yakuakerc; ln --symbolic /home/$USER/.local/share/konsole/Yakuake-$coolor.profile /home/$USER/.local/share/konsole/Yakuake.profile; koi --set-$coolor; yin-yang --set-$coolor
