### ISSUE TITLE
[REQUEST] Categorize themes depending on their dominant color shade (dark/light)

### ISSUE THREAD

**Issue by bphd** [baduhai/Koi#44]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

It's relevant because a lot of software only listen to GTK/QT telling them that dominant is dark/light. And some light themes gives dark variable (Fluent...) and contrary too (Adwaita-dark, Sweet Mars...)

Maybe better, only permit dark dominant themes to be applied in the dark part and same for light

**Comment by baduhai** [comment]
> only permit dark dominant themes to be applied in the dark part and same for light

But what if you're a psychopath and want light themes at night and dark themes diluting the day? 🤔

On a more serious note, I don't know how to do this, otherwise I would have already. Any help would be appreciated.

**Comment by bphd** [comment]
It's not that hard to do properly, because I just told that there is actually a dominant variable in the theme that GTK/QT gives to software for them to work with. You only have to find out where it is and define filtering with that. Filtering with theme name is impossible, because few of them use "dark/light" in their name

And maybe a checkbox to stop that filtering for fools over there and here who want to mix dominant at their risk

**Comment by bphd** [comment]
For example Firefox listen to that variable to set it's own theme on the "auto" theme. So you could search for what Firefox read in that case. That would be the variable to filter

**Comment by bphd** [comment]
VSCode too can detect this variable for example (maybe it's another one, in that case you should use both because it's different variable depending of KDE/Wayland/X11/GTK/QT... and it will permit you to know on what filter each category in the list)

**Comment by baduhai** [comment]
I agree that it's not hard to do, but knowing how to do something in theory, and being able to do it, are two different things. I would welcome any help :smile:

**Comment by baduhai** [comment]
Closed by mistake.

**Comment by bphd** [comment]
I feel that something good in your life happened, motivating you to take time to replenish this project 💪

**Comment by MartinVonReichenberg** [comment]
This idea seems quite far from basic logic.

Closing due to lack of interest, skills and activity . . .

**Comment by bphd** [comment]
Well, maybe not that motivated

**Comment by MartinVonReichenberg** [comment]
> Well, maybe not that motivated

_Yeah,

Not everybody is as smart as masturbating monkeys, you know . . ._
