### ISSUE TITLE
[BUG] KDE color scheme (dark/light) stays at dark even when pressing "light" of Koi

### ISSUE THREAD

**Issue by bphd** [baduhai/Koi#45]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - Distro: [e.g. KDE Neon]
 - Version [e.g. 0.1]

**Additional context**

**Comment by baduhai** [comment]
I probably closed this out of frustration for the lack of info in your bug report. regardless, if you're still facing the issue on the latest version, feel free to open a new issue.
