### ISSUE TITLE
[REQUEST] rename binaries from `Koi` to `koi`

### ISSUE THREAD

**Issue by bphd** [baduhai/Koi#46]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by bphd** [comment]
You closed this as completed. Following bureaucracy, it's already done lol

**Comment by baduhai** [comment]
Close as completed is just the default button, and I'm too lazy to click the drop-down :P

**Comment by baduhai** [comment]
Done :)
