### ISSUE TITLE
Switching gtk to light uses 'Default' until app relaunch

### ISSUE THREAD

**Issue by taprobane99** [baduhai/Koi#49]
I have gtk theme switching set to Breeze/Breeze-dark. When going back to Breeze (dark-->light) Firefox will actually use 'Default' which is Adwaita until I quit FFox and relaunch.

Expected behaviour: switching to gtk light theme uses selected theme even without quitting and relaunching.

**Comment by baduhai** [comment]
This is a Firefox bug, not Koi's fault.
