### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by bphd** [baduhai/Koi#51]
**Describe the bug**

```
kf.service.services: KApplicationTrader: mimeType "x-scheme-handler/file" not found
QSocketNotifier: Can only be used with threads started with QThread
QObject::connect: No such signal QPlatformNativeInterface::systemTrayWindowChanged(QScreen*)
```

**To Reproduce**

```sh
killall Koi; kioclient exec /usr/bin/Koi
```

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - Distro: [e.g. KDE Neon]
 - Version [e.g. 0.1]

Arch latest; Koi latest stable

**Additional context**

**Comment by baduhai** [comment]
Check latest version.
