### ISSUE TITLE
[BUG]Kruner theme not change

### ISSUE THREAD

**Issue by spphinslove** [baduhai/Koi#53]
**Describe the bug**
apply light theme and wait till night
Kruner them not change

**To Reproduce**
1.apply light theme and wait till night
2.boot system,other theme success changed theme to dark,but Krunner still light.

**Screenshots**
![Screenshot_20220731_222734](https://user-images.githubusercontent.com/11383988/182031334-d4a0bc68-37a4-4311-a72b-bb4358fa587b.png)

**Desktop (please complete the following information):**
Operating System: Debian GNU/Linux
KDE Plasma Version: 5.25.3
KDE Frameworks Version: 5.94.0
Qt Version: 5.15.4
Kernel Version: 5.18.0-2-amd64 (64-bit)
Graphics Platform: X11

Distributor ID: Debian
Description:    Debian GNU/Linux bookworm/sid
Release:        testing
Codename:       bookworm

**Comment by baduhai** [comment]
Krunner follows the plasma style, it's not enough to change only the colour scheme.

**Comment by spphinslove** [comment]
![Screenshot_20220802_082541](https://user-images.githubusercontent.com/11383988/182266701-797c10e4-c16e-4be3-82dc-f0af4f479803.png)

**Comment by baduhai** [comment]
Check latest version, if problem persists, open a new issue.
