### ISSUE TITLE
[BUG] PlasmaShell closes with Koi

### ISSUE THREAD

**Issue by bphd** [baduhai/Koi#59]
I think it's known and maybe at the core of how koi works, but it's bothering to not be able to use the desktop just because we close koi

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - Distro: [e.g. KDE Neon]
 - Version [e.g. 0.1]

**Additional context**

**Comment by baduhai** [comment]
Imma need more information than this, the bug report template is there for a reason, please use it.

From what I gather, PlasmaShell crashes when Koi is closed? That definitely shouldn't happen, please provide the information requested on the bug report template, so I can start debugging properly.

**Comment by bphd** [comment]
Arch latest, I don't have the other elements at my disposition

**Comment by bphd** [comment]
AUR

**Comment by MartinVonReichenberg** [comment]
I might try Arch with KDE in VirtualBox to see it too . . .

**Comment by bphd** [comment]
One workaround I found is to restart it until it comes out nicely (with according theme, with Koi opened and in tray app, with plasmashell opened). But it's obviously flawed, because when I'm not lucky, I don't have any window nor bar anymore and I'm nearly stuck

```sh
while true; do set +xv; read; set -xv; killall koi; koi & done
```
