### ISSUE TITLE
[BUG] Koi app does not remain open after ticking the automatic line 

### ISSUE THREAD

**Issue by Da-Viper** [baduhai/Koi#6]
**Describe the bug**
Koi app does not remain open after ticking the automatic line.
the app would launch but not open just send a notification that theme applied ......
the app is not in the system tray as i checked it 

**To Reproduce**
2. Launch the app 
3. Click on the automatic check box 
4.  A pop up below saying "to enable automatic mode koi must be restarted " 
5. Click on the restart button 
6. Viola the app disappears  

**Expected behavior**
the app shoud open when the restart button is clicked 

**Screenshots**

**Desktop (please complete the following information):**
 - Distro: [ Manjaro]
 - Version [ 0.1]

**Additional context**
it happens for both the appimage and the source code

**Comment by baduhai** [comment]
Can't reproduce this issue on my end. Will try to setup a Majaro Live environment to see if I can.

**Comment by Da-Viper** [comment]
here is a video showing the situation i tested it on both the appimage and the src files 

https://youtu.be/jzsVzojRvvY

**Comment by baduhai** [comment]
Replicated the bug successfully. Should be a simple fix, will do it when I have some time.

**Comment by baduhai** [comment]
I also have something in the pipes which should entirely remove the need to restart the application in the first place.

**Comment by baduhai** [comment]
New version should fix this bug. See new release or pull latest changes from Master.
