### ISSUE TITLE
[BUG] Plasma-shell theme do not change without a restart of the shell

### ISSUE THREAD

**Issue by vroger11** [baduhai/Koi#63]
**Describe the bug**
The plasma-shell theme do not switch automatically without a restart of plasmashell

**To Reproduce**
1. set plasma theme for dark and light mode
2. switch from dark to light or light to dark

**Expected behavior**
The theme change immediately

**Desktop (please complete the following information):**
 - Distro: Manjaro Linux
 - Koi Version: last one from master: bc0dfac042132013817a081b61871ff979aa5238
 - Plasma Version: 5.26.3
 - Installation method: it occurs to me from AUR and compiled from source

**Additional context**
It is not reproducible on every computer I have. It appears to me with a fresh installation of Manjaro (with a laptop using intel GPU and CPU).

**Comment by baduhai** [comment]
It seems to me to be distro specific. I'm on NixOS with Plasma 5.26.3 and have been unable to reproduce this bug.

**Comment by MartinVonReichenberg** [comment]
With the inclusion of restarting `krunner` _"patchwork"_ from @vroger11 into `master` branch this 'issue' should no longer be relevant . . .
