### ISSUE TITLE
Changing Window decorations

### ISSUE THREAD

**Issue by Maathias** [baduhai/Koi#67]
When switching between light/dark, window decorations are unchanged.

![image](https://user-images.githubusercontent.com/24920514/219970559-0389c3be-24d2-459b-9fe9-19ca9239bc14.png)

I don't think I have something miss-configured, correct me if I'm wrong.
It would be nice to have an additional toggle for this

**Comment by baduhai** [comment]
If your window decoration doesn't follow the colour scheme, it won't change. Unfortunately, I will not be adding functionality for this, as Plasma is getting functionality for switching colours based on time. Once that is upstream, I will be sunsetting Koi.
