### ISSUE TITLE
[REQUEST] Show main window if the applicaiton is already running

### ISSUE THREAD

**Issue by Shatur** [baduhai/Koi#69]
**Is your feature request related to a problem? Please describe.**

I run this app on Pinephone and we don't have support for system tray. So If I start the app, I can't open it again.

**Describe the solution you'd like**

Open main window of the already running app if the applicaiton is already running. This is how it works with Telegram, for example.

**Comment by MartinVonReichenberg** [comment]
Hello,

As this is intended to be primarily a desktop program, unfortunately there is nothing we could do to make it work in this way - at the moment.

The only way you can do, in the meantime, is to use `htop` terminal program and the pressing `F4` type: `koi` and then `F9` to kill the program manually and reopen it again . . .

Cheers and Good Luck!

**Comment by Shatur** [comment]
> unfortunately there is nothing we could do to make it work in this way

It's possible to show main window if the application is already running. There is a library https://github.com/itay-grudev/SingleApplication. When you detect running second instance you can just show main window.

**Comment by MartinVonReichenberg** [comment]
> > unfortunately there is nothing we could do to make it work in this way
> 
> It's possible to show main window if the application is already running. There is a library https://github.com/itay-grudev/SingleApplication. When you detect running second instance you can just show main window.


_Good then_ 😏
