### ISSUE TITLE
[OTHER] Confusing title for automatic option

### ISSUE THREAD

**Issue by Da-Viper** [baduhai/Koi#7]
the logic behind the automatic button 
you 

you can either click on light/ dark to change the theme 

if you click on the automatic it disables the schedule button( the sunset/ sunrise radio button is always greyed out no matter the condition) 

i think that the automatic button is redundant and should not be there only the schedule and sunset/surise button only 

by choosing schedule it does it by the manual time the user has specified and by choosing sunset/sunrise  it does it automatically .

**Comment by baduhai** [comment]
The idea is that the user has three options; Manual (user manually clicks the buttons light and dark), Schedule (the program automatically switches based on a user-set schedule), and Sunrise/sunset (program automatically calculates when to switch). So the automatic button isn't going anywhere, but perhaps it could me renamed?

**Comment by cyclinggeorgian** [comment]
I agree with original design. It is in line with "Night Color" functionality in the Plasma. Where user gets same options to set activation on:
- sunset/rise (based on the location)
- Always on (on/off toggle) e.i. - manual
- Custom - user defined time frames.

**Comment by baduhai** [comment]
Seeing as there have been no better suggestions, closing.
