### ISSUE TITLE
[OTHER] Wrong link to OpenSUSE packages

### ISSUE THREAD

**Issue by ShintoPlasm** [baduhai/Koi#70]
Hi there,

The current links to OpenSUSE packages lead to empty locations, possibly obsolete. Instead, I strongly recommend linking to the OpenSUSE Software entry, which links to all the existing (and live) community packages of Koi, including Martin VR's one: https://software.opensuse.org/package/Koi

Or maybe specifically recommend using Martin's repo, link at: https://build.opensuse.org/package/show/home%3AMartinVonReichenberg%3AKoi/Koi

**Comment by MartinVonReichenberg** [comment]
All will be re-written and re-mentioned . . .

**Comment by MartinVonReichenberg** [comment]
> Hi there,
> 
> The current links to OpenSUSE packages lead to empty locations, possibly obsolete. Instead, I strongly recommend linking to the OpenSUSE Software entry, which links to all the existing (and live) community packages of Koi, including Martin VR's one: https://software.opensuse.org/package/Koi
> 
> Or maybe specifically recommend using Martin's repo, link at: https://build.opensuse.org/package/show/home%3AMartinVonReichenberg%3AKoi/Koi

Hello,

Here they are:

[OBS](https://build.opensuse.org/package/show/KDE:Extra/koi) | [SUSE Software](https://software.opensuse.org//download.html?project=KDE%3AExtra&package=koi)
