### ISSUE TITLE
[BUG] fatal error: QtDBus: No such file or directory

### ISSUE THREAD

**Issue by bphd** [baduhai/Koi#71]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - Distro: [e.g. KDE Neon]
 - Koi Version: [e.g. 0.1]
 - Plasma Version: [e.g. 5.25.5]
 - Intallation method: [e.g. AppImage/nix/aur/copr/OBS/compiled from source]

**Additional context**

sudo apt install      g++ qtbase5-dev  cmake  libkf5coreaddons-dev  libkf5widgetsaddons-dev libkf5config-dev libkf5package-dev libkf5service-dev kubuntu-desktop; git clone https://github.com/baduhai/Koi.git;      cd Koi;      mkdir build;      cd build;      cmake ../src/;      sudo make;      sudo make install
Reading package lists... Done
Building dependency tree       
Reading state information... Done
g++ is already the newest version (4:9.3.0-1ubuntu2).
libkf5config-dev is already the newest version (5.68.0-0ubuntu1).
libkf5coreaddons-dev is already the newest version (5.68.0-0ubuntu1).
libkf5package-dev is already the newest version (5.68.0-0ubuntu1).
libkf5service-dev is already the newest version (5.68.0-0ubuntu1).
libkf5widgetsaddons-dev is already the newest version (5.68.0-0ubuntu1).
cmake is already the newest version (3.16.3-1ubuntu1.20.04.1).
kubuntu-desktop is already the newest version (1.398.1).
qtbase5-dev is already the newest version (5.12.8+dfsg-0ubuntu2.1).
The following packages were automatically installed and are no longer required:
  
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 272 not upgraded.
fatal: destination path 'Koi' already exists and is not an empty directory.
mkdir: cannot create directory ‘build’: File exists
-- Configuring done
CMake Error at CMakeLists.txt:29 (add_executable):
  Target "koi" links to target "Qt::Core" but the target was not found.
  Perhaps a find_package() call is missing for an IMPORTED target, or an
  ALIAS target is missing?

CMake Error at CMakeLists.txt:29 (add_executable):
  Target "koi" links to target "Qt::DBus" but the target was not found.
  Perhaps a find_package() call is missing for an IMPORTED target, or an
  ALIAS target is missing?

CMake Error at CMakeLists.txt:29 (add_executable):
  Target "koi" links to target "Qt::Gui" but the target was not found.
  Perhaps a find_package() call is missing for an IMPORTED target, or an
  ALIAS target is missing?

CMake Error at CMakeLists.txt:29 (add_executable):
  Target "koi" links to target "Qt::Network" but the target was not found.
  Perhaps a find_package() call is missing for an IMPORTED target, or an
  ALIAS target is missing?

CMake Error at CMakeLists.txt:29 (add_executable):
  Target "koi" links to target "Qt::Test" but the target was not found.
  Perhaps a find_package() call is missing for an IMPORTED target, or an
  ALIAS target is missing?

CMake Error at CMakeLists.txt:29 (add_executable):
  Target "koi" links to target "Qt::Widgets" but the target was not found.
  Perhaps a find_package() call is missing for an IMPORTED target, or an
  ALIAS target is missing?

-- Generating done
CMake Generate step failed.  Build files cannot be regenerated correctly.
[  5%] Automatic MOC and UIC for target koi
[  5%] Built target koi_autogen
[ 11%] Building CXX object CMakeFiles/koi.dir/koi_autogen/mocs_compilation.cpp.o
In file included from /home/$USER/yin/Koi/src/headers/utils.h:6,
                 from /home/$USER/yin/Koi/src/headers/mainwindow.h:5,
                 from /home/$USER/yin/Koi/build/koi_autogen/K6S233IZAZ/moc_mainwindow.cpp:9,
                 from /home/$USER/yin/Koi/build/koi_autogen/mocs_compilation.cpp:4:
/home/$USER/yin/Koi/src/headers/gtk.h:5:10: fatal error: QtDBus: No such file or directory
    5 | #include <QtDBus>
      |          ^~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/koi.dir/build.make:74: CMakeFiles/koi.dir/koi_autogen/mocs_compilation.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:80: CMakeFiles/koi.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
[  5%] Automatic MOC and UIC for target koi
[  5%] Built target koi_autogen
[ 11%] Building CXX object CMakeFiles/koi.dir/koi_autogen/mocs_compilation.cpp.o
In file included from /home/$USER/yin/Koi/src/headers/utils.h:6,
                 from /home/$USER/yin/Koi/src/headers/mainwindow.h:5,
                 from /home/$USER/yin/Koi/build/koi_autogen/K6S233IZAZ/moc_mainwindow.cpp:9,
                 from /home/$USER/yin/Koi/build/koi_autogen/mocs_compilation.cpp:4:
/home/$USER/yin/Koi/src/headers/gtk.h:5:10: fatal error: QtDBus: No such file or directory
    5 | #include <QtDBus>
      |          ^~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/koi.dir/build.make:74: CMakeFiles/koi.dir/koi_autogen/mocs_compilation.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:80: CMakeFiles/koi.dir/all] Error 2
make: *** [Makefile:130: all] Error 2

**Comment by MartinVonReichenberg** [comment]
Hello,
You are missing some of the QT (KDE Framework) **make** dependencies . . .

**Comment by baduhai** [comment]
Sorry I haven't replied to this. Plasma 6 coming out soon will [hopefully](https://invent.kde.org/plasma/plasma-workspace/-/issues/59)  have built-in support for automatic theme changing, at which pointI will retire Koi and archive this repo.

**Comment by bphd** [comment]
> Hello, You are missing some of the QT (KDE Framework) **make** dependencies . . .

I did `sudo apt install g++ qtbase5-dev cmake libkf5coreaddons-dev libkf5widgetsaddons-dev libkf5config-dev libkf5package-dev libkf5service-dev kubuntu-desktop` like the manual requires. I'm supposed to have everything this program needs. Otherwise the manual is not complete (it doesnt say on what it should be done/what we should already have beforehand)

**Comment by MartinVonReichenberg** [comment]
> Sorry I haven't replied to this. Plasma 6 coming out soon will [hopefully](https://invent.kde.org/plasma/plasma-workspace/-/issues/59)  have built-in support for automatic theme changing, at which point I will retire Koi and archive this repo.


*Well, just leave it for those not being among the first getting KDE Plasma 6 onboard............*

**Comment by bphd** [comment]
> Sorry I haven't replied to this. Plasma 6 coming out soon will [hopefully](https://invent.kde.org/plasma/plasma-workspace/-/issues/59) have built-in support for automatic theme changing, at which point I will retire Koi and archive this repo.

From the time it'll be rolled out on stable for everybody your software has quite some time to live, so maybe better maintain it. And even if they implement a tiny function about switching it'll be far from complete and we'll need third party like that software. We will need plugins to support soft, we will need different times and condition, ambient brightness, different thing than total white/black theme, but more accent, and so on

**Comment by MartinVonReichenberg** [comment]
> > Hello, You are missing some of the QT (KDE Framework) **make** dependencies . . .
> 
> I did `sudo apt install g++ qtbase5-dev cmake libkf5coreaddons-dev libkf5widgetsaddons-dev libkf5config-dev libkf5package-dev libkf5service-dev kubuntu-desktop` like the manual requires. I'm supposed to have everything this program needs. Otherwise the manual is not complete (it doesnt say on what it should be done/what we should already have beforehand)



Yup,
It is not complete.

I've tested building Koi only in Virtual Box using Ubuntu 22.10.

**Comment by baduhai** [comment]
I don't want to maintain this anymore, I don't even use it. If somebody wants to fork it, I could link to the fork before I archive this repo, or maybe I'll give somebody commit rights, but I will not be maintaining this in the future (I really haven't been for a while now).

**Comment by MartinVonReichenberg** [comment]
> I don't want to maintain this anymore, I don't even use it. If somebody wants to fork it, I could link to the fork before I archive this repo, or maybe I'll give somebody commit rights, but I will not be maintaining this in the future (I really haven't been for a while now).



*How surprising is that you do not even use it . . .*

**Comment by bphd** [comment]
> > I don't want to maintain this anymore, I don't even use it. If somebody wants to fork it, I could link to the fork before I archive this repo, or maybe I'll give somebody commit rights, but I will not be maintaining this in the future (I really haven't been for a while now).
> 
> _How surprising is that you do not even use it . . ._
> 
> I would write that I do not have enough knowledge to do any changes and/or "improvements", but I wanted to rename the Icon launcher within the notification bar to be showing output name '**Koi**' instead of '**koi**'. And it still shows '**koi**'.

That's me who asked to replace `Koi` to `koi`, because it's like a rule in the unix world, maybe only NetworkManager don't respect it

**Comment by MartinVonReichenberg** [comment]
> > > I don't want to maintain this anymore, I don't even use it. If somebody wants to fork it, I could link to the fork before I archive this repo, or maybe I'll give somebody commit rights, but I will not be maintaining this in the future (I really haven't been for a while now).
> > 
> > _How surprising is that you do not even use it . . ._
> > 
> > I would write that I do not have enough knowledge to do any changes and/or "improvements", but I wanted to rename the Icon launcher within the notification bar to be showing output name '**Koi**' instead of '**koi**'. And it still shows '**koi**'.
> 
> That's me who asked to replace `Koi` to `koi`, because it's like a rule in the unix world, maybe only NetworkManager don't respect it


Hello,
I do not mean the binary executable file,
 But I mean the tray menu entry in KDE toolbar when hoovering with the mouse cursor over the Koi icon in the notification tray:
https://github.com/baduhai/Koi/blob/386c0fea22fc4a110448c4cb7c687cea635ad66a/src/utils.cpp#L25

Even, when I inserted `Koi` instead of `koi` it is still, for some reason, showing `koi` there . . .

Because application's/program's names shown in desktop environment should always start with Capital letters except the ones "standardized" by Unix "philosophy" -- For now . . . . . . . . .

**Comment by MartinVonReichenberg** [comment]
> > > I don't want to maintain this anymore, I don't even use it. If somebody wants to fork it, I could link to the fork before I archive this repo, or maybe I'll give somebody commit rights, but I will not be maintaining this in the future (I really haven't been for a while now).
> > 
> > _How surprising is that you do not even use it . . ._
> > 
> > I would write that I do not have enough knowledge to do any changes and/or "improvements", but I wanted to rename the Icon launcher within the notification bar to be showing output name '**Koi**' instead of '**koi**'. And it still shows '**koi**'.
> 
> That's me who asked to replace `Koi` to `koi`, because it's like a rule in the unix world, maybe only NetworkManager don't respect it


Hello,
I do not mean the binary executable file,
 But I mean the tray menu entry in KDE toolbar when hoovering with the mouse cursor over the Koi icon in the notification tray:
https://github.com/baduhai/Koi/blob/386c0fea22fc4a110448c4cb7c687cea635ad66a/src/utils.cpp#L25

Even, when I inserted `Koi` instead of `koi` it is still, for some reason, showing `koi` there . . .

Because application's/program's names shown in desktop environment should always start with Capital letters except the ones "standardized" by Unix "philosophy" -- For now . . . . . . . . .

**Comment by bphd** [comment]
> > > > I don't want to maintain this anymore, I don't even use it. If somebody wants to fork it, I could link to the fork before I archive this repo, or maybe I'll give somebody commit rights, but I will not be maintaining this in the future (I really haven't been for a while now).
> > > 
> > > 
> > > _How surprising is that you do not even use it . . ._
> > > I would write that I do not have enough knowledge to do any changes and/or "improvements", but I wanted to rename the Icon launcher within the notification bar to be showing output name '**Koi**' instead of '**koi**'. And it still shows '**koi**'.
> > 
> > 
> > That's me who asked to replace `Koi` to `koi`, because it's like a rule in the unix world, maybe only NetworkManager don't respect it
> 
> Hello, I do not mean the binary executable file, But I mean the tray menu entry in KDE toolbar when hoovering with the mouse cursor over the Koi icon in the notification tray:
> 
> https://github.com/baduhai/Koi/blob/386c0fea22fc4a110448c4cb7c687cea635ad66a/src/utils.cpp#L25
> 
> Even, when I inserted `Koi` instead of `koi` it is still, for some reason, showing `koi` there . . .
> 
> Because application's/program's names shown in desktop environment should always start with Capital letters except the ones "standardized" by Unix "philosophy" -- For now . . . . . . . . .

Really it's okay for it to have capital letter everywhere but on the binary executable file especially yeah

**Comment by MartinVonReichenberg** [comment]
> > > > > I don't want to maintain this anymore, I don't even use it. If somebody wants to fork it, I could link to the fork before I archive this repo, or maybe I'll give somebody commit rights, but I will not be maintaining this in the future (I really haven't been for a while now).
> > > > 
> > > > 
> > > > _How surprising is that you do not even use it . . ._
> > > > I would write that I do not have enough knowledge to do any changes and/or "improvements", but I wanted to rename the Icon launcher within the notification bar to be showing output name '**Koi**' instead of '**koi**'. And it still shows '**koi**'.
> > > 
> > > 
> > > That's me who asked to replace `Koi` to `koi`, because it's like a rule in the unix world, maybe only NetworkManager don't respect it
> > 
> > Hello, I do not mean the binary executable file, But I mean the tray menu entry in KDE toolbar when hoovering with the mouse cursor over the Koi icon in the notification tray:
> > 
> > https://github.com/baduhai/Koi/blob/386c0fea22fc4a110448c4cb7c687cea635ad66a/src/utils.cpp#L25
> > 
> > Even, when I inserted `Koi` instead of `koi` it is still, for some reason, showing `koi` there . . .
> > 
> > Because application's/program's names shown in desktop environment should always start with Capital letters except the ones "standardized" by Unix "philosophy" -- For now . . . . . . . . .
> 
> Really it's okay for it to have capital letter everywhere but on the binary executable file especially yeah

Indeed, usually thoughts, names, labels and sentences look way better when they start with Capital letters.

**Comment by MartinVonReichenberg** [comment]
> I don't want to maintain this anymore, I don't even use it. If somebody wants to fork it, I could link to the fork before I archive this repo, or maybe I'll give somebody commit rights, but I will not be maintaining this in the future (I really haven't been for a while now).


Since you have received quite some amount of messages due to the interested in this program, you can now choose what to do next then.

Either give someone (**_full_**) 'rights' to the Koi repository + AUR or let someone to fork it and use it on "his own".

All in all, these couple of requests will **not take more than 70 minute**s of your 'considerate' time . . .


Thank you for any response regarding to this matter,
Martin

**Comment by MartinVonReichenberg** [comment]
> **Describe the bug** A clear and concise description of what the bug is.
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> 1. Go to '...'
> 2. Click on '....'
> 3. Scroll down to '....'
> 4. See error
> 
> **Expected behavior** A clear and concise description of what you expected to happen.
> 
> **Screenshots** If applicable, add screenshots to help explain your problem.
> 
> **Desktop (please complete the following information):**
> 
> * Distro: [e.g. KDE Neon]
> * Koi Version: [e.g. 0.1]
> * Plasma Version: [e.g. 5.25.5]
> * Intallation method: [e.g. AppImage/nix/aur/copr/OBS/compiled from source]
> 
> **Additional context** Add any other context about the problem here.
> 
> sudo apt install g++ qtbase5-dev cmake libkf5coreaddons-dev libkf5widgetsaddons-dev libkf5config-dev libkf5package-dev libkf5service-dev kubuntu-desktop; git clone https://github.com/baduhai/Koi.git; cd Koi; mkdir build; cd build; cmake ../src/; sudo make; sudo make install Reading package lists... Done Building dependency tree Reading state information... Done g++ is already the newest version (4:9.3.0-1ubuntu2). libkf5config-dev is already the newest version (5.68.0-0ubuntu1). libkf5coreaddons-dev is already the newest version (5.68.0-0ubuntu1). libkf5package-dev is already the newest version (5.68.0-0ubuntu1). libkf5service-dev is already the newest version (5.68.0-0ubuntu1). libkf5widgetsaddons-dev is already the newest version (5.68.0-0ubuntu1). cmake is already the newest version (3.16.3-1ubuntu1.20.04.1). kubuntu-desktop is already the newest version (1.398.1). qtbase5-dev is already the newest version (5.12.8+dfsg-0ubuntu2.1). The following packages were automatically installed and are no longer required:
> 
> Use 'sudo apt autoremove' to remove them. 0 upgraded, 0 newly installed, 0 to remove and 272 not upgraded. fatal: destination path 'Koi' already exists and is not an empty directory. mkdir: cannot create directory ‘build’: File exists -- Configuring done CMake Error at CMakeLists.txt:29 (add_executable): Target "koi" links to target "Qt::Core" but the target was not found. Perhaps a find_package() call is missing for an IMPORTED target, or an ALIAS target is missing?
> 
> CMake Error at CMakeLists.txt:29 (add_executable): Target "koi" links to target "Qt::DBus" but the target was not found. Perhaps a find_package() call is missing for an IMPORTED target, or an ALIAS target is missing?
> 
> CMake Error at CMakeLists.txt:29 (add_executable): Target "koi" links to target "Qt::Gui" but the target was not found. Perhaps a find_package() call is missing for an IMPORTED target, or an ALIAS target is missing?
> 
> CMake Error at CMakeLists.txt:29 (add_executable): Target "koi" links to target "Qt::Network" but the target was not found. Perhaps a find_package() call is missing for an IMPORTED target, or an ALIAS target is missing?
> 
> CMake Error at CMakeLists.txt:29 (add_executable): Target "koi" links to target "Qt::Test" but the target was not found. Perhaps a find_package() call is missing for an IMPORTED target, or an ALIAS target is missing?
> 
> CMake Error at CMakeLists.txt:29 (add_executable): Target "koi" links to target "Qt::Widgets" but the target was not found. Perhaps a find_package() call is missing for an IMPORTED target, or an ALIAS target is missing?
> 
> -- Generating done CMake Generate step failed. Build files cannot be regenerated correctly. [ 5%] Automatic MOC and UIC for target koi [ 5%] Built target koi_autogen [ 11%] Building CXX object CMakeFiles/koi.dir/koi_autogen/mocs_compilation.cpp.o In file included from /home/$USER/yin/Koi/src/headers/utils.h:6, from /home/$USER/yin/Koi/src/headers/mainwindow.h:5, from /home/$USER/yin/Koi/build/koi_autogen/K6S233IZAZ/moc_mainwindow.cpp:9, from /home/$USER/yin/Koi/build/koi_autogen/mocs_compilation.cpp:4: /home/$USER/yin/Koi/src/headers/gtk.h:5:10: fatal error: QtDBus: No such file or directory 5 | #include | ^~~~~~~~ compilation terminated. make[2]: *** [CMakeFiles/koi.dir/build.make:74: CMakeFiles/koi.dir/koi_autogen/mocs_compilation.cpp.o] Error 1 make[1]: *** [CMakeFiles/Makefile2:80: CMakeFiles/koi.dir/all] Error 2 make: *** [Makefile:130: all] Error 2 [ 5%] Automatic MOC and UIC for target koi [ 5%] Built target koi_autogen [ 11%] Building CXX object CMakeFiles/koi.dir/koi_autogen/mocs_compilation.cpp.o In file included from /home/$USER/yin/Koi/src/headers/utils.h:6, from /home/$USER/yin/Koi/src/headers/mainwindow.h:5, from /home/$USER/yin/Koi/build/koi_autogen/K6S233IZAZ/moc_mainwindow.cpp:9, from /home/$USER/yin/Koi/build/koi_autogen/mocs_compilation.cpp:4: /home/$USER/yin/Koi/src/headers/gtk.h:5:10: fatal error: QtDBus: No such file or directory 5 | #include | ^~~~~~~~ compilation terminated. make[2]: *** [CMakeFiles/koi.dir/build.make:74: CMakeFiles/koi.dir/koi_autogen/mocs_compilation.cpp.o] Error 1 make[1]: *** [CMakeFiles/Makefile2:80: CMakeFiles/koi.dir/all] Error 2 make: *** [Makefile:130: all] Error 2



Hello,

You are missing _RUN Dependencies_ - and not _BUILD Dependencies_, actually; here they are:

**Make Dependencies:**

```
g++
build-essential
cmake
qtbase5-dev
qtbase5-dev-tools
libkf5config-dev
libkf5coreaddons-dev
libkf5widgetsaddons-dev
```


**Run Dependecies:**
```
libkf5configcore5
libkf5config-data
libkf5configgui5
libkf5guiaddons5
libkf5guiaddons-data
libkf5coreaddons5
libkf5coreaddons-data
libqt5core5a
libkf5dbusaddons5
libkf5dbusaddons-data
libqt5gui5
libkf5guiaddons5
libkf5guiaddons-data
libqt5network5
libqt5test5
libkf5widgetsaddons5
libkf5widgetsaddons-data
libqt5xml5
libqt5xmlpatterns5
```

_I shall update the build/run instructions later on in README and Wiki page._

**Comment by MartinVonReichenberg** [comment]
@bphd 
[Here](https://github.com/baduhai/Koi/releases) is the binary release for Debian/Ubuntu.
