### ISSUE TITLE
[BUG] KDE Plasma dependency issues

### ISSUE THREAD

**Issue by winstonrc** [baduhai/Koi#74]
**Describe the bug**
A few packages required by KDE Plasma have updated their names to add a 5 to the end presumably for the upcoming release of Plasma 6. They are unable to update since koi (installed from the aur) is dependent on the old package names.

See here for the relevant change: https://gitlab.archlinux.org/archlinux/packaging/packages/attica5/-/commit/71b095187bc4ecaaa1947d0e23b5bec20c596093

AUR: https://aur.archlinux.org/packages/koi

Accordingly, the following errors occur when updating these packages with koi installed:

```
:: installing kconfig5 (5.111.0-1) breaks dependency 'kconfig' required by koi
:: installing kcoreaddons5 (5.111.0-1) breaks dependency 'kcoreaddons' required by koi
:: installing kwidgetsaddons5 (5.111.0-1) breaks dependency 'kwidgetsaddons' required by koi
:: installing kpackage5 (5.111.0-1) breaks dependency 'kpackage' required by koi
```

**To Reproduce**
Update the following packages via a package manager:

- kconfig -> kconfig5
- kcoreaddons -> kcoreaddons5
- kwidgetsaddons -> kwidgetsaddons5
- kpackage -> kpackage5

**Expected behavior**
Update the package dependencies so that the other packages can update without breaking koi.

**Desktop (please complete the following information):**
 - Distro: Arch Linux - KDE Plasma
 - Koi Version: 0.2.3-2
 - Plasma Version: 5.27.8
 - Intallation method: aur

**Comment by winstonrc** [comment]
Looks like this is an issue with the aur package and not the source code itself, so marking as code.
Relevant updates for this issue can be followed here: https://aur.archlinux.org/packages/koi

**Comment by MartinVonReichenberg** [comment]
@winstonrc 
The packages `koi` and `koi-git` have been fully updated now . . .
