### ISSUE TITLE
[OTHER] Packaging guidelines

### ISSUE THREAD

**Issue by michalszmidt** [baduhai/Koi#77]
Hi,

thank you for developing this missing piece of KDE!

As a packager I could not create template file for Koi for Void Linux build system.
It doesn't recognize it as a cmake project.
I could not find any workaround for it except forking repo and setting src as top root of the project

I'm not expert but most cmake projects I saw had CMakeLists.txt in the root of the project. I guess this should fix it.

Could you tweak and move CMakeLists.txt to the top root of the project then create a tag 0.2.4.1?

Also I opened https://github.com/void-linux/void-packages/issues/47761 so they could handle this scenario.

**Comment by MartinVonReichenberg** [comment]
`cmake -S ${srcdir}(name-version)/src/ -B ${builddir}/src/build/`


Look at the AUR PKGBUILD file, it should be the same . . .

**Comment by MartinVonReichenberg** [comment]
So,
Did you succeed at [Issue#47761](https://github.com/void-linux/void-packages/issues/47761) , @michalszmidt 
?_?

**Comment by michalszmidt** [comment]
Hi,

Unfortunately, they refused to support this kind of solution.

This is because this build system is highly automated (not like AUR) and ready for cross-compilation. You don't call any cmake command there, you just set the build-style to cmake and all args are composed and called automatically.

That way you don't mess with dependencies, args, envs. All this is handled automatically. 
It works perfectly with rust, go etc. with fixed project structure

I guess if you want to keep current project structure, I will have to do sth. like set build-style to manual and override all phases (haven't ever really tried, just overrode single functions)

**Comment by MartinVonReichenberg** [comment]
> EDIT:
> 
> It turned out that my test environment was weirdly broken and with help of void-linux team compilation passes now.
> 
> I'll tweak it more (add desktop files etc.) and open pull request for Koi to the official void repo! Thanks for your time.

What desktop files?

All is mentioned in `Koi/src/resources` and there is already a `koi.desktop` file inside `Koi/src`.

**Comment by michalszmidt** [comment]
> What desktop files?
> 
> All is mentioned in `Koi/src/resources/(resources.qrc)` and there is already a `koi.desktop` file inside `Koi/src`.

Right. Everything is there.

Finally submitted https://github.com/void-linux/void-packages/pull/47985 PR
