### ISSUE TITLE
[REQUEST] Please port koi from Plasma 5 to Plasma 6

### ISSUE THREAD

**Issue by emk2203** [baduhai/Koi#79]
**Is your feature request related to a problem? Please describe.**
Plasma 6 is released and already in the standard Arch repositories. When I try to build `koi` from the AUR PKGBUILD, it wants to rely on several Plasma 5 libraries. Do you have a schedule for a Plasma 6 release of `koi`?

**Describe the solution you'd like**
I would like to have a release which builds for Plasma 6 without relying on Plasma 5 libraries.

**Describe alternatives you've considered**
I have considered installing it 'as-is' and risk breaking things on Plasma 6.

**Additional context**
I would like to see a proper updated `koi` because [there's already one case of a poorly implemented port from Plasma 5 to Plasma 6](https://www.reddit.com/r/kde/comments/1bje0ck/warning_global_themes_and_widgets_created_by_3rd/) where the user's `/home/$USER` was wiped and only the need for escalated access prevented  a `rm -rf` of the whole system.

**Comment by MartinVonReichenberg** [comment]
> **Is your feature request related to a problem? Please describe.**
> Plasma 6 is released and already in the standard Arch repositories. When I try to build `koi` from the AUR PKGBUILD, it wants to rely on several Plasma 5 libraries. Do you have a schedule for a Plasma 6 release of `koi`?
> 
> **Describe the solution you'd like**
> I would like to have a release which builds for Plasma 6 without relying on Plasma 5 libraries.
> 
> **Describe alternatives you've considered**
> I have considered installing it 'as-is' and risk breaking things on Plasma 6.
> 
> **Additional context**
> I would like to see a proper updated `koi` because [there's already one case of a poorly implemented port from Plasma 5 to Plasma 6](https://www.reddit.com/r/kde/comments/1bje0ck/warning_global_themes_and_widgets_created_by_3rd/) where the user's `/home/$USER` was wiped and only the need for escalated access prevented  a `rm -rf` of the whole system.


Hello,
I will look into it after I get Arch distro up and running again. I do not use Arch on a daily basis. It might take 2-3-4 days as I am currently not so much into it.

As for maintenance of feature-requests of Koi, there is going to be none because @baduhai decided to drop interest in maintaining this program and I lack certain skills/experiences to be doing so, so do not expect anything positive regarding this matter (or any other matter as well) . . .

**Comment by MartinVonReichenberg** [comment]
Cannot get trough this while using _all_ **KF6** and **QT6** libraries only:   

```
-- Configuring done (0.8s)
-- Generating done (0.0s)
-- Build files have been written to: /home/martin/.AUR/Koi/koi/NEW/src/Koi-0.2.5/src/build
[  0%] Built target koi_autogen_timestamp_deps
[  5%] Automatic MOC and UIC for target koi
[  5%] Built target koi_autogen
[ 11%] Automatic RCC for resources/resources.qrc
[ 16%] Building CXX object CMakeFiles/koi.dir/koi_autogen/mocs_compilation.cpp.o
[ 22%] Building CXX object CMakeFiles/koi.dir/libs/SunRise.cpp.o
[ 27%] Building CXX object CMakeFiles/koi.dir/about.cpp.o
[ 33%] Building CXX object CMakeFiles/koi.dir/colorscheme.cpp.o
[ 38%] Building CXX object CMakeFiles/koi.dir/gtk.cpp.o
[ 44%] Building CXX object CMakeFiles/koi.dir/icons.cpp.o
[ 50%] Building CXX object CMakeFiles/koi.dir/kvantumstyle.cpp.o
[ 55%] Building CXX object CMakeFiles/koi.dir/license.cpp.o
/home/martin/.AUR/Koi/koi/NEW/src/Koi-0.2.5/src/license.cpp: In constructor ‘License::License(QWidget*)’:
/home/martin/.AUR/Koi/koi/NEW/src/Koi-0.2.5/src/license.cpp:8:18: error: variable ‘QFile license’ has initializer but incomplete type
    8 |     QFile license(":/resources/license.txt");
      |                  ^
/home/martin/.AUR/Koi/koi/NEW/src/Koi-0.2.5/src/license.cpp:9:25: error: incomplete type ‘QFile’ used in nested name specifier
    9 |     license.open(QFile::ReadOnly);
      |                         ^~~~~~~~
make[2]: *** [CMakeFiles/koi.dir/build.make:193: CMakeFiles/koi.dir/license.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:167: CMakeFiles/koi.dir/all] Error 2
make: *** [Makefile:136: all] Error 2
==> ERROR: A failure occurred in build().
    Aborting...
martin@Lenovo-ThinkCentre-M75q--Arch-Linux-KDE
```

_Any clues ?--?_

**Comment by MartinVonReichenberg** [comment]
@emk2203 

Done, 
See [Releases](https://github.com/baduhai/Koi/releases/tag/0.3) for more . . .
