### ISSUE TITLE
[OTHER] Two config files koirc and Koirc

### ISSUE THREAD

**Issue by kupiqu** [baduhai/Koi#8]
**Describe the bug**

Configuration is split in two different files, probably a typo.

**To Reproduce**

Just check ~/config/koirc and ~/config/Koirc

**Comment by baduhai** [comment]
Not quite a bug, I was aware of it before, it's just an unintended outcome of using QFileDialog. Though I suppose we can merge the two files into ~/.config/Koirc but only at the expense of current users having to manually migrate their settings. Not a big deal I think, Koi is only in version 0.1.1 afterall, these kinks are to be expected.

**Comment by baduhai** [comment]
I do believe this no longer an issue. I don't remember when exactly I fixed it, but I did at some point, I think.
