### ISSUE TITLE
Application Style switching

### ISSUE THREAD

**Issue by J-Cake** [baduhai/Koi#80]
**Is your feature request related to a problem? Please describe.**
In the rare case that setting the `Application Style` is necessary, the option to do so would be amazing.
![Screenshot_20240406_150042](https://github.com/baduhai/Koi/assets/29561775/30f56a08-b9cc-47fc-aa87-b127400c1879)

**Describe the solution you'd like**
The way colours and wallpapers and whatnot are specifiable should just also include an `Application Style` setting. 

**Describe alternatives you've considered**
Frankly, I've been using a script to do this automatically, but it never really worked and since moving to my new system, I haven't been bothered to debug it, but that's what I would have done.

**Additional context**
I'm not sure whether the `Kvantum theme` setting does the same thing, although I could be wrong

**Comment by MartinVonReichenberg** [comment]
Hello,

`Kvantum Style` offers themes that are created using **Kvantum theming** program and should be listed in **Koi**.
`Application Style` section, however, is missing along with **Mouse Cursors** _(Cursor selection)_.

All these will unfortunately will not be worked on within Koi. . .

Cheers from Liberec

**Comment by MartinVonReichenberg** [comment]
Duplicate of **ISSUE**: **#100**
