### ISSUE TITLE
[REQUEST] Change display brightness

### ISSUE THREAD

**Issue by major-mayer** [baduhai/Koi#81]
**Is your feature request related to a problem? Please describe.**
Yes, in a sense. I found out that Plasma is able to control the display brightness of my screen.
But there is apparently no way to automatically control the brightness based on the time.

**Describe the solution you'd like**
It would be great if we could use Koi to lower the brightness of a screen automatically when the night mode is activated.

**Describe alternatives you've considered**
Manually switching the brightness is quite annoying, because it has to be done twice per day.
A normal setting for this would be ideal of course, but I think the KDE devs first need to implement automatic dark mode switching.

**Additional context**

**Comment by MartinVonReichenberg** [comment]
> **Is your feature request related to a problem? Please describe.**
> Yes, in a sense. I found out that Plasma is able to control the display brightness of my screen.
> But there is apparently no way to automatically control the brightness based on the time.
> 
> **Describe the solution you'd like**
> It would be great if we could use Koi to lower the brightness of a screen automatically when the night mode is activated.
> 
> **Describe alternatives you've considered**
> Manually switching the brightness is quite annoying, because it has to be done twice per day.
> A normal setting for this would be ideal of course, but I think the KDE devs first need to implement automatic dark mode switching.
> 
> **Additional context**
> Add any other context or screenshots about the feature request here.
> 



Hello,
Yup,
It was said by some that the automatic Light/Dark theme switching according to time within day is going to be a part of KDE Plasma 6/6.1, but it never came across as true after all . . .

This, unfortunately, will not be worked on due to lack of interest and in my case "know-how".

Cheers!

**Comment by major-mayer** [comment]
That's a pity, but thanks for the quick response.

**Comment by MartinVonReichenberg** [comment]
@major-mayer 

Setting display brightness is **already implemented** in the latest KDE Plasma 6.

_Closing the issue here then . . ._

**Comment by major-mayer** [comment]
Ah really, I haven't noticed this yet, but maybe I'm not on the very latest version.
In the meanwhile, I'm quite happy with https://github.com/digitaltrails/vdu_controls
