### ISSUE TITLE
[REQUEST] Checkmark for "Updating system configuration" appearance toggle.

### ISSUE THREAD

**Issue by toboil-features** [baduhai/Koi#87]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
I wish to see a check mark in settings to toggle "Updating system configuration..." window from appearing at all.

**Describe alternatives you've considered**
This one is just fine.

**Additional context**
![Screenshot](https://github.com/baduhai/Koi/assets/160222185/ec1f77b6-c304-43c1-b9e3-e5fcdd2e95f6)

**Comment by MartinVonReichenberg** [comment]
Hello,

What do you mean?


Nothing of this is a part of the Koi program. 

Koi is not software created by the KDE Plasma developers and this pop-up window has nothing to do with Koi as such.
