### ISSUE TITLE
[OTHER] Add (Not yet available) to Sunset/Sunrise option

### ISSUE THREAD

**Issue by kupiqu** [baduhai/Koi#9]
Just a suggestion to inform users about this, so they don't think something is misbehaving

**Comment by baduhai** [comment]
Fair enough.

**Comment by H-M-H** [comment]
It might be helpful to have a look how KWin does it for night colors: https://github.com/KDE/kwin/tree/master/colorcorrection

**Comment by major-mayer** [comment]
Yeah it would be really nice if this could be bound to the already existing night color switching from KDE. Maybe there exists some hook/ DBus thing (i don't know how this works).

**Comment by baduhai** [comment]
Has been available since 0.1.3, I just never closed this issue.

**Comment by major-mayer** [comment]
Okay but the current mechanism is not bound to the existing night color switch from KDE right?
This is a standalone implementation, which seems to be working, but it would be more convenient if the user wouldn't have to look up the coordinates and possibly have two different time points for night colour and dark theme switch.

**Comment by baduhai** [comment]
Yeah, it's not the smoothest experience. I think using civil twilight will be a big improvement, but I'm not sure how to hook into plasma, and use the pre existing sunset/rise options.
