### ISSUE TITLE
Struggling to install[OTHER]

### ISSUE THREAD

**Issue by kamikazebob** [baduhai/Koi#90]
Plasma vers 5.27.11 Kubuntu 22.04

Receiving this issue when trying to install - any help much appreciated !

**CMake Warning at CMakeLists.txt:22 (find_package):
  By not providing "FindKF6Config.cmake" in CMAKE_MODULE_PATH this project
  has asked CMake to find a package configuration file provided by
  "KF6Config", but CMake did not find one.

  Could not find a package configuration file provided by "KF6Config" with
  any of the following names:

    KF6ConfigConfig.cmake
    kf6config-config.cmake

  Add the installation prefix of "KF6Config" to CMAKE_PREFIX_PATH or set
  "KF6Config_DIR" to a directory containing one of the above files.  If
  "KF6Config" provides a separate development package or SDK, be sure it has
  been installed.

CMake Warning at CMakeLists.txt:23 (find_package):
  By not providing "FindKF6CoreAddons.cmake" in CMAKE_MODULE_PATH this
  project has asked CMake to find a package configuration file provided by
  "KF6CoreAddons", but CMake did not find one.

  Could not find a package configuration file provided by "KF6CoreAddons"
  with any of the following names:

    KF6CoreAddonsConfig.cmake
    kf6coreaddons-config.cmake

  Add the installation prefix of "KF6CoreAddons" to CMAKE_PREFIX_PATH or set
  "KF6CoreAddons_DIR" to a directory containing one of the above files.  If
  "KF6CoreAddons" provides a separate development package or SDK, be sure it
  has been installed.

CMake Warning at CMakeLists.txt:24 (find_package):
  By not providing "FindKF6WidgetsAddons.cmake" in CMAKE_MODULE_PATH this
  project has asked CMake to find a package configuration file provided by
  "KF6WidgetsAddons", but CMake did not find one.

  Could not find a package configuration file provided by "KF6WidgetsAddons"
  with any of the following names:

    KF6WidgetsAddonsConfig.cmake
    kf6widgetsaddons-config.cmake

  Add the installation prefix of "KF6WidgetsAddons" to CMAKE_PREFIX_PATH or
  set "KF6WidgetsAddons_DIR" to a directory containing one of the above
  files.  If "KF6WidgetsAddons" provides a separate development package or
  SDK, be sure it has been installed.

CMake Error at CMakeLists.txt:25 (find_package):
  Could not find a package configuration file provided by "QT" with any of
  the following names:

    Qt6Config.cmake
    qt6-config.cmake

  Add the installation prefix of "QT" to CMAKE_PREFIX_PATH or set "QT_DIR" to
  a directory containing one of the above files.  If "QT" provides a separate
  development package or SDK, be sure it has been installed.**

**Comment by MartinVonReichenberg** [comment]
Hello,

Anything named: KF6 / QT6 **rename to** KF5 / QT5 in `../src/CMakeLists.txt` and then try again . . .

**Comment by kamikazebob** [comment]
Perfect that worked a treat thanks !
