### ISSUE TITLE
[OTHER] it is not an issue but a big thank

### ISSUE THREAD

**Issue by Cherkah** [baduhai/Koi#92]
after one feature request on kde.bugs about "brightness & color" one guy have mentioned this app.

thanks a lot for your job, this app is amazing (qt6, simple, effective...). Kde should promote this app

regards

**Comment by MartinVonReichenberg** [comment]
Hello,

Thank you for your feedback.

Could you provide me/us the link about mentioning Koi into integration with KDE Plasma?

Thank you . . .

**Comment by RokeJulianLockhart** [comment]
> https://github.com/baduhai/Koi/issues/92#issuecomment-2352990418

@MartinVonReichenberg, it's https://bugs.kde.org/show_bug.cgi?id=408563#c24.

**Comment by Cherkah** [comment]
[bugs.kde](https://bugs.kde.org/show_bug.cgi?id=408563)

> ... about mentioning Koi into integration with KDE Plasma?

i never talked about 'integration with KDE plasma' but see it buy your self..
regards

**Comment by MartinVonReichenberg** [comment]
_Not relevant anymore . . . . ._
