### ISSUE TITLE
[BUG] Unable to set wallpaper via Koi.

### ISSUE THREAD

**Issue by RokeJulianLockhart** [baduhai/Koi#93]
**Describe the bug**

I'm unable to switch wallpapers via Koi:

> https://github.com/user-attachments/assets/59bd2eaa-9e78-4a71-a662-8666e6bf8937

**To Reproduce**

> ![Screenshot_20240918_165702](https://github.com/user-attachments/assets/d7cc35f7-7f00-4125-b066-1e686324ecf8)

**Expected behaviour**

The wallpaper should switch when I switch themes via Koi's GUI.

**Desktop**

1. Distro:              https://packages.fedoraproject.org/pkgs/plasma-desktop/plasma-desktop/fedora-40-updates.html
1. Koi Version:         https://copr.fedorainfracloud.org/coprs/birkch/Koi/build/7677830/
1. Plasma Version:      https://koji.fedoraproject.org/koji/rpminfo?rpmID=39683231
1. Installation method: https://copr.fedorainfracloud.org/coprs/birkch/Koi/repo/fedora-40/birkch-Koi-fedora-40.repo

**Comment by MartinVonReichenberg** [comment]
I, actually, have never tried switching wallpapers . . .

**Comment by MartinVonReichenberg** [comment]
@RokeJulianLockhart 

Hello,
I just installed **Koi** on **Fedora 41** with latest updates from **COPR** and it **DOES WORK** for me . . .

![Screenshot_20240928_225153](https://github.com/user-attachments/assets/79423437-cf50-449c-8627-eb7f4bfafa92)
![Screenshot_20240928_225234](https://github.com/user-attachments/assets/256cb7b1-70cd-419a-9961-9aafb18cfa1c)
![Screenshot_20240928_225256](https://github.com/user-attachments/assets/5468769f-eec7-4d4c-8da3-73fbaf27b858)

**Comment by RokeJulianLockhart** [comment]
> https://github.com/baduhai/Koi/issues/93#issuecomment-2380892680

@MartinVonReichenberg, unfortunately, it doesn't for me:

#### **Reproduction**

1.	My `$HOME/.config/koirc` is:

	<blockQuote>
	
	```desktop
	[General]
	current=Dark
	latitude=52.87
	longitude=1.264
	notify=2
	schedule=2
	schedule-type=sun
	start-hidden=2
	
	[ColorScheme]
	dark=/usr/share/color-schemes/BreezeDark.colors
	enabled=true
	light=/usr/share/color-schemes/BreezeLight.colors
	
	[GTKTheme]
	dark=Breeze-Dark
	enabled=true
	light=Breeze
	
	[IconTheme]
	dark=breeze-dark
	enabled=true
	light=breeze
	
	[KvantumStyle]
	dark=
	enabled=false
	light=
	
	[PlasmaStyle]
	dark=breeze-dark
	enabled=true
	light=breeze-light
	
	[Wallpaper]
	dark=/home/RokeJulianLockhart/Pictures/KCMs/#2a2e32.PNG
	enabled=true
	light=/home/RokeJulianLockhart/Pictures/KCMs/#eff0f1.PNG
	
	```
	
	</blockQuote>

1.	I recreate my configuration:

	> https://github.com/user-attachments/assets/e74f8b6f-106a-4399-bcea-0a510514a3d0

1.	My *new* `$HOME/.config/koirc` is:

	<blockQuote>

	```desktop
	[General]
	current=Dark
	latitude=52.87
	longitude=1.264
	notify=2
	schedule=2
	schedule-type=sun
	start-hidden=2
	
	[ColorScheme]
	dark=/usr/share/color-schemes/BreezeDark.colors
	enabled=true
	light=/usr/share/color-schemes/BreezeLight.colors
	
	[GTKTheme]
	dark=Breeze-Dark
	enabled=true
	light=Breeze
	
	[IconTheme]
	dark=breeze-dark
	enabled=true
	light=breeze
	
	[KvantumStyle]
	dark=
	enabled=false
	light=
	
	[PlasmaStyle]
	dark=breeze-dark
	enabled=true
	light=breeze-light
	
	[Wallpaper]
	dark=/home/RokeJulianLockhart/Pictures/KCMs/#2a2e32.PNG
	enabled=true
	light=/home/RokeJulianLockhart/Pictures/KCMs/#eff0f1.PNG

	```

	</blockQuote>

	Its SHA512 hash is `f34fcfb74828162d7150484e6e6e9ced9d98a1272e06d2aef276ebe976afa28b1a9df2b41d8cfb5b774327563b6a81f7858a700d3ecc2615b021e72a2c8e8ff6`. Unfortunately, I didn't acquire the hash of the previous file, but ascertaining it from the duplicated content should be trivial. I haven't bothered.

**Comment by MartinVonReichenberg** [comment]
@RokeJulianLockhart 

A new [release - 0.4](https://github.com/baduhai/Koi/releases/tag/0.4) of Koi is out, check it out. And let us know how it goes for you . . .

**Comment by RokeJulianLockhart** [comment]
> https://github.com/baduhai/Koi/issues/93#issuecomment-2544029225

@MartinVonReichenberg, it appears to work now:

https://github.com/user-attachments/assets/fb2facee-161c-4c08-baf7-915d2207b74a
