### ISSUE TITLE
[REQUEST] feature to stop notification

### ISSUE THREAD

**Issue by Cherkah** [baduhai/Koi#95]
**Is your feature request related to a problem? Please describe.**
 I'm always frustrated when i cannot deactivate notification bell in my floating panel.
have already  try to stop this behavior in system notification but doesn't work.
Why notify me about koi activity if i already observe its activity by my desktop's modification? 

**Describe the solution you'd like**
implement an feature to stop notifications

**Describe alternatives you've considered**
koi is present in the system notification settings.  but none of these settings can stop koi notifications.
is this a bug?

![kde system settings notification](https://github.com/user-attachments/assets/78e3083e-1bb9-4f30-a09e-d278890aa92c)

regards

**Comment by Cherkah** [comment]
ok forget about my previous "request".... i didn't see that this was already present int the koi's GUI.
can close it
regards.

**Comment by MartinVonReichenberg** [comment]
It should be co-existing with the KDe Plasma Settings, but as mentioned, it is an in-app feature . . .
![Screenshot_20240928_224553](https://github.com/user-attachments/assets/00743086-3c52-4ce8-bf8a-369ee1b36a0f)
